version: '3.8'
services:
  techstore-db:
    image: postgres:15-alpine
    container_name: techstore-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: techstore
    ports:
      - "5432:5432"
    volumes:
      - techstore-db-data:/var/lib/postgresql/data


volumes:
  techstore-db-data:
